---
name: black_format

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  black_format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@25.1.0
        with:
          options: "--check --verbose"
