---
name: pip_audit

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '10 2 * * 1,3'

jobs:
  pip_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up Poetry
        uses: snok/install-poetry@v1

      - name: Install poetry-plugin-export
        run: |
          poetry self add poetry-plugin-export

      - name: Generate requirements
        run: |
          poetry export --format=requirements.txt --output=requirements.txt
          poetry export --with dev --format=requirements.txt --output=dev-requirements.txt

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt dev-requirements.txt
...
